services:
  - type: web
    name: cadastro-fastapi
    env: python
    buildCommand: "pip install -r CadastroFastAPI/requirements.txt"
    startCommand: "uvicorn CadastroFastAPI.main:app --host 0.0.0.0 --port 10000"
    rootDirectory: CadastroFastAPI
    envVars:
      - key: DATABASE_URL
        value: "postgresql://user:password@host:port/database"

