services:
  - type: web
    name: cadastro-fastapi
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn CadastroFastAPI.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
